### ISSUE TITLE
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: rankcard() got an unexpected keyword argument 'user'

### ISSUE THREAD

**Issue by Joseph-Joestar-hamon** [BlazenBoi/canvacord#1]
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: rankcard() got an unexpected keyword argument 'user'

**Comment by BlazenBoi** [comment]
Is this issue still happening? If so please provide your code so I can try to help.

**Comment by BlazenBoi** [comment]
I am closing this bc of no response. You can still reopen this with the ReOpen Button.
