### ISSUE TITLE
A few minor details

### ISSUE THREAD

**Issue by GeckoPie007** [BlazenBoi/canvacord#4]
Hello. I was using your awesome module and I found a few bugs.
First of all, if you have a lot of xp or if your username is long than the username covers the xp counter. Also, if a users status is set to Idle then nothing appears. Finally, for some reason the user profile image is moved somewhat to the top left. Other than that, this module is really great and I love it.  Thanks, GeckoPie.
![image](https://user-images.githubusercontent.com/78640902/130031237-6de5826f-37f1-48df-9661-05434e3ae228.png)
![image](https://user-images.githubusercontent.com/78640902/130031830-d1b035d7-2a95-4677-919d-352e5888df16.png)

**Comment by BlazenBoi** [comment]
Ok I will work on fixing this. I need to figure out how the original canvacord does it and I’ll replicate that.

**Comment by BlazenBoi** [comment]
Ok I figured out how it worked. It basically just shrunk the text as it got longer past a certain point, so I will try to replicate this in a new update.

**Comment by BlazenBoi** [comment]
I will also try to figure out why the idle bug is occurring.

**Comment by BlazenBoi** [comment]
Ok if you update to the newest version the idle thing should be fixed. I am still working on the whole no running into it but it takes a massively long name (like 20+ characters. I am going to not cut it off even through canvacord normally does, so it might look weird if someone has a massive massive name.) to hit it now. If you have any more problems just ask.
![circle](https://user-images.githubusercontent.com/65360471/130173448-caa29301-fc3b-4f97-9a63-350e6601b0c3.png)
[](url)
![circle](https://user-images.githubusercontent.com/65360471/130172343-b30f5d9f-dff7-4174-b856-4c037aa7ba27.png)

If the error persists please re-open this issue, or make another issue.
