### ISSUE TITLE
Add the option to disable the black background

### ISSUE THREAD

**Issue by AxizY** [BlazenBoi/canvacord#5]
Sometimes I want to see the background fully without the black smaller background covering it up.

**Comment by BlazenBoi** [comment]
I will try to make this a thing in the next few days. Sorry I dont check the github like ever. If you want faster support go into the discord.

**Comment by AxizY** [comment]
I've actually modified my own version to suite these requests, though it is a bit behind. I will make a pull request someday. 👍🏽
